### ISSUE TITLE
Raspbian - mv: cannot stat ‘t-be.gmo’mv: cannot stat ‘t-bg.gmo’: No such file or directory

### ISSUE THREAD

**Issue by stuaxo** [PetrosKataras/GStreamerScripts#2]
I had some trouble building on raspbian

``` sh
[snipped]
make[2]: Entering directory '/home/pi/gst/master/gstreamer/po'
test ! -f ./gstreamer-1.0.pot || \
  test -z "af.gmo az.gmo be.gmo bg.gmo ca.gmo cs.gmo da.gmo de.gmo en_GB.gmo eo.gmo es.gmo el.gmo eu.gmo fi.gmo fr.gmo gl.gmo hr.gmo hu.gmo id.gmo it.gmo ja.gmo lt.gmo nb.gmo nl.gmo pl.gmo pt_BR.gmo ro.gmo ru.gmo rw.gmo sk.gmo sl.gmo sq.gmo sr.gmo sv.gmo tr.gmo uk.gmo vi.gmo zh_CN.gmo zh_TW.gmo" || make af.gmo az.gmo be.gmo bg.gmo ca.gmo cs.gmo da.gmo de.gmo en_GB.gmo eo.gmo es.gmo el.gmo eu.gmo fi.gmo fr.gmo gl.gmo hr.gmo hu.gmo id.gmo it.gmo ja.gmo lt.gmo nb.gmo nl.gmo pl.gmo pt_BR.gmo ro.gmo ru.gmo rw.gmo sk.gmo sl.gmo sq.gmo sr.gmo sv.gmo tr.gmo uk.gmo vi.gmo zh_CN.gmo zh_TW.gmo
make[3]: Entering directory '/home/pi/gst/master/gstreamer/po'
rm -f af.gmo && : -c --statistics -o af.gmo af.po
rm -f be.gmo && : -c --statistics -o be.gmo be.po
rm -f az.gmo && : -c --statistics -o az.gmo az.po
rm -f bg.gmo && : -c --statistics -o bg.gmo bg.po
mv: cannot stat ‘t-af.gmo’: No such file or directory
Makefile:159: recipe for target 'af.gmo' failed
make[3]: *** [af.gmo] Error 1
make[3]: *** Waiting for unfinished jobs....
mv: cannot stat ‘t-az.gmo’: No such file or directory
mv: cannot stat ‘t-be.gmo’mv: cannot stat ‘t-bg.gmo’: No such file or directory
: No such file or directory
Makefile:159: recipe for target 'be.gmo' failed
make[3]: *** [be.gmo] Error 1
Makefile:159: recipe for target 'bg.gmo' failed
make[3]: *** [bg.gmo] Error 1
Makefile:159: recipe for target 'az.gmo' failed
make[3]: *** [az.gmo] Error 1
make[3]: Leaving directory '/home/pi/gst/master/gstreamer/po'
Makefile:196: recipe for target 'stamp-po' failed
make[2]: *** [stamp-po] Error 2
make[2]: Leaving directory '/home/pi/gst/master/gstreamer/po'
Makefile:758: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/pi/gst/master/gstreamer'
Makefile:663: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by PetrosKataras** [comment]
Hey, not sure what is happening here to be honest but this looks like an extremely weird output :0 ...How did you run the script exactly ?

**Comment by stuaxo** [comment]
Ah, I did `$ sh create-gst-uninstalled-env.sh`  as I noticed it didn't have the executable bit set.

**Comment by stuaxo** [comment]
Trying again with as `./create-gst-uninstalled-env.sh` after chmod +x

**Comment by PetrosKataras** [comment]
`sh create-gst-uninstalled-env.sh` should be fine for the master branch. The master branch is the default if none is specified which means that the compilation of current master GStreamer might be broken currently for whatever reason on Raspbian or in general..

**Comment by PetrosKataras** [comment]
Can you fetch the latest change I pushed and run :  

`sh create-gst-uninstalled-env.sh -b 1.9.2 --omx-branch 1.9.2`

to try an older branch and see if this works for you? 

I am away from the RPi now so if this also doesn't work then I would have to check it on the device later on today..

**Comment by stuaxo** [comment]
It looks like I was missing gettext, once I installed that everything seemed to build OK.

My app uses python3.5 + glib.

To get it working I build my own python3.5, pygobject, glib and pycairo.     I think pygobject and/or glib will need to built with some awareness of these libraries, would I need to set a prefix or something to make this work ?

**Comment by PetrosKataras** [comment]
I m not sure how library dependencies are getting resolved in Pythonland but for a C++ binary you can just enter the gst uninstalled env and then run your app and the dynamic linker does the trick of picking the correct version of GStreamer ( since you are running your app inside the newly created gst environment ).

You can try first this which is fast since it doesn't require modifications/rebuilding of your app and see if it picks the latest version otherwise you can enter the environment and try to build inside there your own objects. If dependency resolving happens through pkgconfig in your build system you shouldn't need to prefix anything since the env setups the paths appropriately.

**Comment by stuaxo** [comment]
Cheers, I will give this a go when I get some time.

WRT to the initial conversation in this ticket, it's worth adding gettext to the things to apt-get.
